# dev 文件只在 dev 环境下生效。文件的位置只要在 resources 下即可，但是必须以 application- 开头。
# 端口号
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 201314
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

sleeve:
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000